from . import help
from . import start
from . import kitoblar_majmuasi
from . import kutubxona_manzillar
from . import kitobdokon_manzillar
from . import support
from . import admin_xabar
from . import admin
from . import echo
